subscription SubscriptionUsers {
  users {
    id
    name
    created_at
    updated_at
  }
}

mutation CreateUser($name: String!) {
  insert_users_one(object: { name: $name }) {
    id
    name
  }
}

mutation UpdateUser($id: Int!, $name: String!) {
  update_users_by_pk(pk_columns: { id: $id }, _set: { name: $name }) {
    id
    name
  }
}

mutation DeleteUser($id: Int!) {
  delete_users_by_pk(id: $id) {
    id
    name
  }
}
